[project]
name = "alerta-energetica-colombia"
version = "0.1.0"
description = "Sistema de alerta temprana energetica que predice estres en el SIN colombiano correlacionando datos climaticos, hidrologicos y de demanda en tiempo real"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.5.4",
    "jupyterlab>=4.6.0",
    "pandas<3.0.0",
    "plotly>=7.1.0",
    "pydataxm>=0.3.17",
    "requests>=2.31.0",
    "sodapy>=2.2.0",
]
